### ISSUE TITLE
beginner/advanced references

### ISSUE THREAD

**Issue by dmison** [node-girls-australia/express-workshop#5]
There's a few times that readers are directed to sites like w3schools for reference.  While those sites are often good for beginners they are not canonical reference and rarely offer a complete picture.  

Suggest also including links to things like https://developer.mozilla.org and differentiating them as "advanced" or something.  Not sure what the best terminology to use there is.

**Comment by anchat1990** [comment]
Hmm.. maybe something along the lines of - "for more detailed documentation..."?

**Comment by anchat1990** [comment]
This is done, if there are any issues please feel free to create a pull request 😊
